"""contador diario del cronista

Revision ID: 830aafc4921d
Revises: de4586251bfd
Create Date: 2026-09-15 22:53:44.111588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '830aafc4921d'
down_revision: Union[str, Sequence[str], None] = 'de4586251bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uso_diario',
    sa.Column('dia', sa.Date(), nullable=False),
    sa.Column('llamadas', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('dia')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uso_diario')
    # ### end Alembic commands ###
