"""usuarios y partidas

Revision ID: b571c8a23e27
Revises: 
Create Date: 2026-09-15 20:50:23.851469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b571c8a23e27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('correo', sa.String(length=320), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('hash_contrasena', sa.String(length=255), nullable=False),
    sa.Column('preferencias', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_table('partidas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=60), server_default='', nullable=False),
    sa.Column('oficio', sa.Integer(), server_default='0', nullable=False),
    sa.Column('objeto_ini', sa.Integer(), server_default='0', nullable=False),
    sa.Column('retrato', sa.Integer(), server_default='0', nullable=False),
    sa.Column('turno', sa.Integer(), server_default='0', nullable=False),
    sa.Column('vida', sa.Integer(), server_default='10', nullable=False),
    sa.Column('vida_max', sa.Integer(), server_default='10', nullable=False),
    sa.Column('oro', sa.Integer(), server_default='0', nullable=False),
    sa.Column('inv', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('armas', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('rasgos', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('gastados', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('lugar', sa.String(length=120), server_default='', nullable=False),
    sa.Column('ambiente', sa.String(length=120), server_default='', nullable=False),
    sa.Column('prosa', sa.Text(), server_default='', nullable=False),
    sa.Column('opciones', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('log', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('completa', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('escena', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('opt_dificultad', sa.String(length=20), nullable=True),
    sa.Column('opt_duracion', sa.String(length=20), nullable=True),
    sa.Column('opt_sellos', sa.Boolean(), nullable=True),
    sa.Column('terminada', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('muerto', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('titulo_final', sa.String(length=120), nullable=True),
    sa.Column('epilogo', sa.Text(), nullable=True),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partidas_usuario_id'), 'partidas', ['usuario_id'], unique=False)
    op.create_index('uq_partida_en_curso_por_usuario', 'partidas', ['usuario_id'], unique=True, postgresql_where=sa.text('NOT terminada'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_partida_en_curso_por_usuario', table_name='partidas', postgresql_where=sa.text('NOT terminada'))
    op.drop_index(op.f('ix_partidas_usuario_id'), table_name='partidas')
    op.drop_table('partidas')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
